service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-south-1

functions:
  app:
    handler: index.handler
    events:
      - http:
        path: schedules
        method: post

resources:
  Resources:
    database:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: 20
        DBInstanceClass: db.t2.micro
        Engine: postgres
        MasterUsername:
          Ref: ${env:DBUSERNAME}
        MasterUserPassword:
          Ref: ${env:DBPASSWORD}
