service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-south-1

functions:
  app:
    handler: index.handler
    events:
      - http:
        path: schedules
        method: post
